---
abstract: 'Perl extension to test if an OS is supported by Siebel CRM'
author:
  - 'Alceu Rodrigues de Freitas Junior <arfreitas@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 1.22
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-AssertOS-OSFeatures-SupportsSiebel
no_index:
  directory:
    - t
    - inc
requires:
  Devel::CheckOS: 1.71
version: 0.01
